[package]
name = "codenames"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
pyo3 = "0.18.1"
rand = "0.8.5"
